version: "3.9"
services:
  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    image: highlyai-api:dev
    command: uvicorn api.app:app --host 0.0.0.0 --port 8080 --reload
    ports:
      - "8080:8080"
    volumes:
      - ./api:/app/api       
      - /app/.venv             
    environment:
      - PYTHONUNBUFFERED=1